# Generated by Django 6.0.4 on 2026-04-10 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fournisseur', models.CharField(max_length=150)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('pays', models.CharField(default='Cameroun', max_length=80)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fournisseur',
                'ordering': ['nom_fournisseur'],
            },
        ),
        migrations.CreateModel(
            name='CommandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=20, unique=True)),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('date_livraison_reelle', models.DateField(blank=True, null=True)),
                ('statut_commande', models.CharField(choices=[('En attente', 'En attente'), ('Confirmée', 'Confirmée'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée')], default='En attente', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='commandes', to='stock.fournisseur')),
            ],
            options={
                'db_table': 'commande_achat',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_piece', models.CharField(max_length=60, unique=True)),
                ('designation', models.CharField(max_length=200)),
                ('categorie', models.CharField(blank=True, max_length=80, null=True)),
                ('unite', models.CharField(default='pièce', max_length=20)),
                ('prix_unitaire_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seuil_alerte', models.PositiveIntegerField(default=5)),
                ('actif', models.BooleanField(default=True)),
                ('fournisseurs', models.ManyToManyField(blank=True, related_name='pieces', to='stock.fournisseur')),
            ],
            options={
                'db_table': 'piece',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.PositiveIntegerField()),
                ('prix_unitaire_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_recue', models.PositiveIntegerField(default=0)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.commandeachat')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stock.piece')),
            ],
            options={
                'db_table': 'ligne_commande',
                'unique_together': {('commande', 'piece')},
            },
        ),
        migrations.AddField(
            model_name='commandeachat',
            name='pieces',
            field=models.ManyToManyField(related_name='commandes', through='stock.LigneCommande', to='stock.piece'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_en_stock', models.PositiveIntegerField(default=0)),
                ('quantite_reservee', models.PositiveIntegerField(default=0)),
                ('localisation', models.CharField(blank=True, max_length=150, null=True)),
                ('date_derniere_maj', models.DateTimeField(auto_now=True)),
                ('piece', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='stock.piece')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
