# Generated by Django 6.0.4 on 2026-04-10 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipements', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_embauche', models.DateField()),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'technicien',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='TypeIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duree_estimee_h', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'type_intervention',
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_planifiee', models.DateField()),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('description_panne', models.TextField(blank=True, null=True)),
                ('rapport_technicien', models.TextField(blank=True, null=True)),
                ('statut_intervention', models.CharField(choices=[('Planifiée', 'Planifiée'), ('En cours', 'En cours'), ('Terminée', 'Terminée'), ('Annulée', 'Annulée')], default='Planifiée', max_length=20)),
                ('duree_heures', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('priorite', models.CharField(choices=[('Urgente', 'Urgente'), ('Haute', 'Haute'), ('Normale', 'Normale'), ('Basse', 'Basse')], default='Normale', max_length=10)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='interventions', to='equipements.equipement')),
            ],
            options={
                'db_table': 'intervention',
                'ordering': ['-date_planifiee'],
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_affectation', models.CharField(choices=[('Principal', 'Principal'), ('Assistant', 'Assistant')], default='Principal', max_length=15)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interventions.intervention')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='interventions.technicien')),
            ],
            options={
                'db_table': 'affectation',
                'unique_together': {('intervention', 'technicien')},
            },
        ),
        migrations.AddField(
            model_name='intervention',
            name='techniciens',
            field=models.ManyToManyField(related_name='interventions', through='interventions.Affectation', to='interventions.technicien'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='type_intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='interventions.typeintervention'),
        ),
        migrations.CreateModel(
            name='UtilisationPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_utilisee', models.PositiveIntegerField(default=1)),
                ('prix_unitaire_applique', models.DecimalField(decimal_places=2, max_digits=10)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interventions.intervention')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stock.piece')),
            ],
            options={
                'db_table': 'utilisation_piece',
                'unique_together': {('intervention', 'piece')},
            },
        ),
        migrations.AddField(
            model_name='intervention',
            name='pieces',
            field=models.ManyToManyField(related_name='interventions', through='interventions.UtilisationPiece', to='stock.piece'),
        ),
    ]
