# Generated by Django 6.0.4 on 2026-04-10 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_devis', models.CharField(max_length=20, unique=True)),
                ('date_devis', models.DateField(auto_now_add=True)),
                ('validite_jours', models.PositiveIntegerField(default=30)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19.25, max_digits=5)),
                ('statut_devis', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Envoyé', 'Envoyé'), ('Accepté', 'Accepté'), ('Refusé', 'Refusé'), ('Expiré', 'Expiré')], default='Brouillon', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='devis', to='clients.client')),
            ],
            options={
                'db_table': 'devis',
                'ordering': ['-date_devis'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=20, unique=True)),
                ('date_facture', models.DateField(auto_now_add=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19.25, max_digits=5)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('statut_paiement', models.CharField(choices=[('Impayée', 'Impayée'), ('Partielle', 'Partielle'), ('Payée', 'Payée')], default='Impayée', max_length=20)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='factures', to='clients.client')),
                ('devis', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture', to='facturation.devis')),
            ],
            options={
                'db_table': 'facture',
                'ordering': ['-date_facture'],
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.devis')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stock.piece')),
            ],
            options={
                'db_table': 'ligne_devis',
                'unique_together': {('devis', 'piece')},
            },
        ),
        migrations.AddField(
            model_name='devis',
            name='pieces',
            field=models.ManyToManyField(related_name='devis', through='facturation.LigneDevis', to='stock.piece'),
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.facture')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stock.piece')),
            ],
            options={
                'db_table': 'ligne_facture',
                'unique_together': {('facture', 'piece')},
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='pieces',
            field=models.ManyToManyField(related_name='factures', through='facturation.LigneFacture', to='stock.piece'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('Espèces', 'Espèces'), ('Mobile Money', 'Mobile Money'), ('Virement', 'Virement'), ('Chèque', 'Chèque')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paiements', to='facturation.facture')),
            ],
            options={
                'db_table': 'paiement',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
