# Generated by Django 6.0.4 on 2026-04-10 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=80)),
                ('modele', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('type_equipement', models.CharField(choices=[('Split', 'Split'), ('Cassette', 'Cassette'), ('Multi-split', 'Multi-split'), ('Armoire frigorifique', 'Armoire frigorifique'), ('Chambre froide', 'Chambre froide'), ('Autre', 'Autre')], max_length=30)),
                ('puissance_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_installation', models.DateField()),
                ('localisation', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('En service', 'En service'), ('En panne', 'En panne'), ('Décommissionné', 'Décommissionné')], default='En service', max_length=20)),
                ('garantie_fin', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='equipements', to='clients.client')),
            ],
            options={
                'db_table': 'equipement',
                'ordering': ['marque', 'modele'],
            },
        ),
    ]
