# Generated by Django 4.1.13 on 2026-04-16 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_id'),
        ('equipements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
