# Generated by Django 6.0.4 on 2026-04-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('prenom_client', models.CharField(blank=True, max_length=100, null=True)),
                ('type_client', models.CharField(choices=[('Particulier', 'Particulier'), ('Entreprise', 'Entreprise')], max_length=20)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'client',
                'ordering': ['nom_client'],
            },
        ),
    ]
